defmodule Ayo.Repo.Migrations.AddCategoryUniqueCategoryIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:categories, [:name, :category_type],
             name: "categories_unique_category_index"
           )
  end

  def down do
    drop_if_exists unique_index(:categories, [:name, :category_type],
                     name: "categories_unique_category_index"
                   )
  end
end
